// <auto-generated />
namespace SalonLesanj.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_new_fields_photo_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_new_fields_photo_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201706052033491_remove_new_fields_photo_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
